#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  1 14:17:18 2024

@author: s1984454
"""

import numpy as np
import matplotlib.pyplot as plt

def cov_cross_element(array1, array2):
    
    cov = np.cov(array1, array2, ddof = 0)
    
    return cov[0,1]

def construct_cov_array(matrix1, matrix2 ):
    
    cov_array = np.zeros(3)
    
    for i in range(3):
        cov_array[i] = cov_cross_element(matrix1[:,i], matrix2[:,i])
        
    return cov_array

base_path = 'Data/SAMPLES_run_10_'
indices = [0,1,3]
labels = ['rho_0', 'rK', 'Psi']
m = 10

samples = np.loadtxt(f'{base_path}{0}.txt')
n = len(samples)//2
xi_bar = np.zeros((m,3))
si_2 = np.zeros((m,3))
total_sum = 0

for i in range(m):
    
    samples = np.loadtxt(f'{base_path}{i}.txt')
    samples = samples[n:, indices]
    
    xi_bar[i,:] = np.mean(samples, axis = 0)
    si_2[i,:] = np.var(samples, axis = 0)
    
    total_sum += np.sum(samples, axis = 0)

mu_hat = xdotdot = total_sum / (n*m)

squared_centered_means = (xi_bar - np.tile(xdotdot, (m,1)))**2

B_n = np.sum(squared_centered_means, axis = 0) / (m-1)
W = np.mean(si_2, axis = 0)

sigma_hat_2 = (n-1)/n * W + B_n

root_V_hat = np.sqrt(sigma_hat_2 + B_n/m) 

var_si = np.var(si_2, axis = 0)

cov1 = construct_cov_array(si_2, xi_bar**2)
cov2 = construct_cov_array(si_2, xi_bar)
var_V_hat = np.square((n-1)/n)/m * var_si + np.square((m+1)/(m*n))*((2*n**2)/(m-1))* B_n**2 + (2*(m+1)*(n-1))/(m**2*n) *(cov1 - 2 * xdotdot * cov2) 
df = 2 * root_V_hat**4/var_V_hat

root_Rhat = np.sqrt((root_V_hat**2 / W) * (df/(df-2)))

# for i in range(3):
    
#     fig1, ax1 = plt.subplots(1,1)
#     ax1.scatter(x = range(m), y = xi_bar[:,i], marker = 'x')
#     ax1.set_xlabel('Run')
#     ax1.set_ylabel(labels[i] + ' mean')
    
#     fig2, ax2 = plt.subplots(1,1)
#     ax2.scatter(x = range(m), y = si_2[:,i], marker = 'x')
#     ax2.set_xlabel('Run')
#     ax2.set_ylabel(labels[i] + ' variance')
    
for i in range(3):
    for j in range(i,3):
        
        fig3, ax3 = plt.subplots(1,1)
        ax3.scatter(xi_bar[:,i], xi_bar[:,j], marker = 'x')
        






